# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.30

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/vikash/Documents/placementProjects/LibEase

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/vikash/Documents/placementProjects/LibEase

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/vikash/Documents/placementProjects/LibEase/CMakeFiles /home/vikash/Documents/placementProjects/LibEase//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/vikash/Documents/placementProjects/LibEase/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named library

# Build rule for target.
library: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 library
.PHONY : library

# fast build rule for target.
library/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/library.dir/build.make CMakeFiles/library.dir/build
.PHONY : library/fast

src/add_book.o: src/add_book.cpp.o
.PHONY : src/add_book.o

# target to build an object file
src/add_book.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/library.dir/build.make CMakeFiles/library.dir/src/add_book.cpp.o
.PHONY : src/add_book.cpp.o

src/add_book.i: src/add_book.cpp.i
.PHONY : src/add_book.i

# target to preprocess a source file
src/add_book.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/library.dir/build.make CMakeFiles/library.dir/src/add_book.cpp.i
.PHONY : src/add_book.cpp.i

src/add_book.s: src/add_book.cpp.s
.PHONY : src/add_book.s

# target to generate assembly for a file
src/add_book.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/library.dir/build.make CMakeFiles/library.dir/src/add_book.cpp.s
.PHONY : src/add_book.cpp.s

src/auth.o: src/auth.cpp.o
.PHONY : src/auth.o

# target to build an object file
src/auth.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/library.dir/build.make CMakeFiles/library.dir/src/auth.cpp.o
.PHONY : src/auth.cpp.o

src/auth.i: src/auth.cpp.i
.PHONY : src/auth.i

# target to preprocess a source file
src/auth.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/library.dir/build.make CMakeFiles/library.dir/src/auth.cpp.i
.PHONY : src/auth.cpp.i

src/auth.s: src/auth.cpp.s
.PHONY : src/auth.s

# target to generate assembly for a file
src/auth.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/library.dir/build.make CMakeFiles/library.dir/src/auth.cpp.s
.PHONY : src/auth.cpp.s

src/display_book.o: src/display_book.cpp.o
.PHONY : src/display_book.o

# target to build an object file
src/display_book.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/library.dir/build.make CMakeFiles/library.dir/src/display_book.cpp.o
.PHONY : src/display_book.cpp.o

src/display_book.i: src/display_book.cpp.i
.PHONY : src/display_book.i

# target to preprocess a source file
src/display_book.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/library.dir/build.make CMakeFiles/library.dir/src/display_book.cpp.i
.PHONY : src/display_book.cpp.i

src/display_book.s: src/display_book.cpp.s
.PHONY : src/display_book.s

# target to generate assembly for a file
src/display_book.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/library.dir/build.make CMakeFiles/library.dir/src/display_book.cpp.s
.PHONY : src/display_book.cpp.s

src/display_members.o: src/display_members.cpp.o
.PHONY : src/display_members.o

# target to build an object file
src/display_members.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/library.dir/build.make CMakeFiles/library.dir/src/display_members.cpp.o
.PHONY : src/display_members.cpp.o

src/display_members.i: src/display_members.cpp.i
.PHONY : src/display_members.i

# target to preprocess a source file
src/display_members.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/library.dir/build.make CMakeFiles/library.dir/src/display_members.cpp.i
.PHONY : src/display_members.cpp.i

src/display_members.s: src/display_members.cpp.s
.PHONY : src/display_members.s

# target to generate assembly for a file
src/display_members.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/library.dir/build.make CMakeFiles/library.dir/src/display_members.cpp.s
.PHONY : src/display_members.cpp.s

src/edit_profile.o: src/edit_profile.cpp.o
.PHONY : src/edit_profile.o

# target to build an object file
src/edit_profile.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/library.dir/build.make CMakeFiles/library.dir/src/edit_profile.cpp.o
.PHONY : src/edit_profile.cpp.o

src/edit_profile.i: src/edit_profile.cpp.i
.PHONY : src/edit_profile.i

# target to preprocess a source file
src/edit_profile.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/library.dir/build.make CMakeFiles/library.dir/src/edit_profile.cpp.i
.PHONY : src/edit_profile.cpp.i

src/edit_profile.s: src/edit_profile.cpp.s
.PHONY : src/edit_profile.s

# target to generate assembly for a file
src/edit_profile.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/library.dir/build.make CMakeFiles/library.dir/src/edit_profile.cpp.s
.PHONY : src/edit_profile.cpp.s

src/issue_book.o: src/issue_book.cpp.o
.PHONY : src/issue_book.o

# target to build an object file
src/issue_book.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/library.dir/build.make CMakeFiles/library.dir/src/issue_book.cpp.o
.PHONY : src/issue_book.cpp.o

src/issue_book.i: src/issue_book.cpp.i
.PHONY : src/issue_book.i

# target to preprocess a source file
src/issue_book.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/library.dir/build.make CMakeFiles/library.dir/src/issue_book.cpp.i
.PHONY : src/issue_book.cpp.i

src/issue_book.s: src/issue_book.cpp.s
.PHONY : src/issue_book.s

# target to generate assembly for a file
src/issue_book.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/library.dir/build.make CMakeFiles/library.dir/src/issue_book.cpp.s
.PHONY : src/issue_book.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/library.dir/build.make CMakeFiles/library.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/library.dir/build.make CMakeFiles/library.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/library.dir/build.make CMakeFiles/library.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/return_book.o: src/return_book.cpp.o
.PHONY : src/return_book.o

# target to build an object file
src/return_book.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/library.dir/build.make CMakeFiles/library.dir/src/return_book.cpp.o
.PHONY : src/return_book.cpp.o

src/return_book.i: src/return_book.cpp.i
.PHONY : src/return_book.i

# target to preprocess a source file
src/return_book.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/library.dir/build.make CMakeFiles/library.dir/src/return_book.cpp.i
.PHONY : src/return_book.cpp.i

src/return_book.s: src/return_book.cpp.s
.PHONY : src/return_book.s

# target to generate assembly for a file
src/return_book.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/library.dir/build.make CMakeFiles/library.dir/src/return_book.cpp.s
.PHONY : src/return_book.cpp.s

src/search_book.o: src/search_book.cpp.o
.PHONY : src/search_book.o

# target to build an object file
src/search_book.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/library.dir/build.make CMakeFiles/library.dir/src/search_book.cpp.o
.PHONY : src/search_book.cpp.o

src/search_book.i: src/search_book.cpp.i
.PHONY : src/search_book.i

# target to preprocess a source file
src/search_book.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/library.dir/build.make CMakeFiles/library.dir/src/search_book.cpp.i
.PHONY : src/search_book.cpp.i

src/search_book.s: src/search_book.cpp.s
.PHONY : src/search_book.s

# target to generate assembly for a file
src/search_book.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/library.dir/build.make CMakeFiles/library.dir/src/search_book.cpp.s
.PHONY : src/search_book.cpp.s

src/search_member.o: src/search_member.cpp.o
.PHONY : src/search_member.o

# target to build an object file
src/search_member.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/library.dir/build.make CMakeFiles/library.dir/src/search_member.cpp.o
.PHONY : src/search_member.cpp.o

src/search_member.i: src/search_member.cpp.i
.PHONY : src/search_member.i

# target to preprocess a source file
src/search_member.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/library.dir/build.make CMakeFiles/library.dir/src/search_member.cpp.i
.PHONY : src/search_member.cpp.i

src/search_member.s: src/search_member.cpp.s
.PHONY : src/search_member.s

# target to generate assembly for a file
src/search_member.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/library.dir/build.make CMakeFiles/library.dir/src/search_member.cpp.s
.PHONY : src/search_member.cpp.s

src/utils.o: src/utils.cpp.o
.PHONY : src/utils.o

# target to build an object file
src/utils.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/library.dir/build.make CMakeFiles/library.dir/src/utils.cpp.o
.PHONY : src/utils.cpp.o

src/utils.i: src/utils.cpp.i
.PHONY : src/utils.i

# target to preprocess a source file
src/utils.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/library.dir/build.make CMakeFiles/library.dir/src/utils.cpp.i
.PHONY : src/utils.cpp.i

src/utils.s: src/utils.cpp.s
.PHONY : src/utils.s

# target to generate assembly for a file
src/utils.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/library.dir/build.make CMakeFiles/library.dir/src/utils.cpp.s
.PHONY : src/utils.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... library"
	@echo "... src/add_book.o"
	@echo "... src/add_book.i"
	@echo "... src/add_book.s"
	@echo "... src/auth.o"
	@echo "... src/auth.i"
	@echo "... src/auth.s"
	@echo "... src/display_book.o"
	@echo "... src/display_book.i"
	@echo "... src/display_book.s"
	@echo "... src/display_members.o"
	@echo "... src/display_members.i"
	@echo "... src/display_members.s"
	@echo "... src/edit_profile.o"
	@echo "... src/edit_profile.i"
	@echo "... src/edit_profile.s"
	@echo "... src/issue_book.o"
	@echo "... src/issue_book.i"
	@echo "... src/issue_book.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/return_book.o"
	@echo "... src/return_book.i"
	@echo "... src/return_book.s"
	@echo "... src/search_book.o"
	@echo "... src/search_book.i"
	@echo "... src/search_book.s"
	@echo "... src/search_member.o"
	@echo "... src/search_member.i"
	@echo "... src/search_member.s"
	@echo "... src/utils.o"
	@echo "... src/utils.i"
	@echo "... src/utils.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

